run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - gosec
    - misspell
    - revive

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
