global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "rate-limiter"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["rate-limiter:8080"]
        labels:
          service: "distributed-rate-limiter"
          env: "production"
